from sqlalchemy import Column, BigInteger, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from database import Base

class Product(Base):
    __tablename__ = "products"
    __table_args__ = {"schema": "wda"}

    id = Column(BigInteger, primary_key=True, index=True)
    category_id = Column(BigInteger, ForeignKey("wda.categories.id", ondelete="CASCADE"))
    original_id = Column(BigInteger)
    name = Column(Text, nullable=False)
    logo = Column(Text)
    quantity = Column(Text)
    image = Column(Text)
    description = Column(Text)
    width = Column(Text)
    ingredientes = Column(Text)
    venta = Column(Text)
    envasado = Column(Text)
    nutri_porcion = Column(Text)
    nutri_valor_energetico_gr = Column(Text)
    nutri_valor_energetico_pct = Column(Text)
    nutri_carbohidratos_gr = Column(Text)
    nutri_carbohidratos_pct = Column(Text)
    nutri_azucares_totales_gr = Column(Text)
    nutri_azucares_totales_pct = Column(Text)
    nutri_azucares_anadidos_gr = Column(Text)
    nutri_azucares_anadidos_pct = Column(Text)
    nutri_proteinas_gr = Column(Text)
    nutri_proteinas_pct = Column(Text)
    nutri_grasas_totales_gr = Column(Text)
    nutri_grasas_totales_pct = Column(Text)
    nutri_grasas_saturadas_gr = Column(Text)
    nutri_grasas_saturadas_pct = Column(Text)
    nutri_grasas_trans_gr = Column(Text)
    nutri_grasas_trans_pct = Column(Text)
    nutri_fibra_alimentaria_gr = Column(Text)
    nutri_fibra_alimentaria_pct = Column(Text)
    nutri_sodio_gr = Column(Text)
    nutri_sodio_pct = Column(Text)
    nutri_calcio_gr = Column(Text)
    nutri_calcio_pct = Column(Text)
    nutri_valores_diarios = Column(Text)
    color_fondo_vaquitas = Column(Text)
    color_vaquitas = Column(Text)
    color_letras_logo = Column(Text)
    color_firma = Column(Text)
    color_detalles = Column(Text)
    color_fondo_letras = Column(Text)
    color_queso = Column(Text)
    color_texto1 = Column(Text)
    color_nombreypeso = Column(Text)
    color_donemilio = Column(Text)
    color_fondologo = Column(Text)
    color_fondocantprod = Column(Text)
    color_cantprod = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
